services:
  redis:
    image: redis/redis-stack-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    environment:
      - REDIS_ARGS=--save 10 1 --loglevel warning
    volumes:
      - ./data/redis:/data
  bot:
    build: .
    restart: always
    env_file: bot.env
    depends_on:
      redis:
        condition: service_healthy
